import = [
    "~/.config/alacritty/themes/themes/github_dark.toml"
]

[env]
HW = "HW"

[window]
dynamic_padding = true
decorations = "Buttonless"
opacity=0.9
blur=true
option_as_alt="Both"

[font]
size=12

[mouse]
bindings = [
{ mouse = "Right" , action = "Paste" },
]

[selection]
save_to_clipboard = true
